language: node_js

node_js:
  - '4'

cache:
  directories:
  - node_modules
  - _assets/vendor

before_script:
  - npm install -g bower

script:
  - bundle
  - bundle exec rake --trace

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
  repo: Ohjeah/Ohjeah.github.io
  target_branch: master
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
