source: src
destination: public
url: markusqua.de

title: "Markus Quade"

repo: http://github.com/Ohjeah/Ohjeah.github.io-source

unpublished: false
future: false

# Build settings
permalink   : /:year/:title/

# Author settings
author:
  first_name: Markus
  last_name: Quade
  title_suffix: PhD
  address : Potsdam, Germany
  job      : Physicist
  email    : schreib@markusqua.de
  web      : http://www.markusqua.de
  url      : http://www.markusqua.de
  github   : Ohjeah
  orcid    : 0000-0002-9123-048X
  gscholar : rGjuWxAAAAAJ


og_locale: "en_US"

plugins:
  - jekyll/scholar
  - jekyll-pandoc
  - jekyll-assets
  - jekyll-last-modified-at

encoding: utf-8

scholar:
  bibliography_template: "bibliography"
  source:       "./_assets/vendor/bib"
  bibliography: "ref.bib"
  repository: "./dl"
  style:        "./_assets/csl/ieee-with-url.csl"
  sort_by:      year
  order:        descending
  group_by:     type
  group_order:  ascending
  type_order:   [misc, article, books, inproceedings, theses]
  type_names:   {misc: Preprints}
  #bibliography_group_tag: [h3, h4, h5, b]
  bibliography_list_tag: "ul"

assets:
  cdn:
    baseurl: true
  sources:
    - _assets/vendor
    - _assets/vendor/css
    - _assets/vendor/fonts
    - _assets/vendor/js
  compress:
    css:  sassc
    js:   uglifier
