title: "Markus"
title2: "Quade" # default: ""
description: ""
keywords: "symbolic regression genetic programming"
#url: stat.physik.uni-potsdam.de
url: markusqua.de
#baseurl: /~mquade
#baseurl: ""

disqus_shortname: mquade
repo: http://github.com/Ohjeah/Ohjeah.github.io-source
comments: true

unpublished: false
future: false

# Build settings
permalink   : /:year/:title/


source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Markus Quade"
  job      : "physicist"
  bio      : "My research promotes genetic programming based symbolic regression and its application to dynamical systems. I am broadly interested in time series prediction, system identification, control theory, and synchronization."
  email    : mquade@uni-potsdam.de
  url      : http://www.stat.physik.uni-potsdam.de/~mquade/
  github   : http://github.com/Ohjeah
  twitter  : https://twitter.com/ohjeah
  orcid    : 0000-0002-9123-048X
  gscholar : rGjuWxAAAAAJ


og_locale: "en_US"

plugins:
  - bourbon
  - jekyll-paginate
  - jekyll/scholar
  - jekyll-pandoc
  - jekyll-assets

encoding: utf-8

## Markdown Parser
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge


include: ['.htaccess', 'keybase.txt', "pages"]
exclude: ['Gemfile', 'Gemfile.lock', 'bower.json', 'Rakefile', 'node_modules', 'LICENSE.md', 'README.md', '.vscode', ".tavis-ci.yml"]
scholar:
  bibliography_template: bibliography
  source: ./_bib/
  repository: ./dl
  style:        ./_assets/bib/ieee-with-url.csl
  sort_by:      year
  order:        descending
  group_by:     type
  group_order:  ascending
  type_order:   [misc, article, books, inproceedings, theses]
  type_names:   {misc: Preprints}
  #bibliography_group_tag: [h3, h4, h5, b]
  bibliography_list_tag: "ul"

assets:
  compress:
      css: sass
      js: uglifier
  assets:
      - "*.csl"
      - "*.eot"
      - "*.woff"
      - "*.ttf"
      - "*.svg"

  digest: false
  sources:
    - _assets/bower
    - _assets/bib
